### ISSUE TITLE
About elr = 0x400000

### ISSUE THREAD

**Issue by Boreas618** [idlebo/OS-23Fall-FDU#10]
这里的0x400000指向什么地址？

<img width="326" alt="Screenshot 2023-10-28 at 1 15 55 PM" src="https://github.com/idlebo/OS-23Fall-FDU/assets/98612013/7c3c7156-ee75-4ac6-9742-fc7357763f74">

**Comment by idlebo** [comment]
0x400000 指向的内容就在这段代码的上面：

![image](https://github.com/idlebo/OS-23Fall-FDU/assets/95092670/af7b0106-72ca-45eb-af67-36b6a1e6a640)

从代码中可以看出，我们将 loop_start 放在 0x400000 的地方，下面是 loop_start 对应的代码（在 loop.S 中）：

![image](https://github.com/idlebo/OS-23Fall-FDU/assets/95092670/8d66a029-fa17-4972-bdb1-eab9001e8411)

**Comment by w568w** [comment]
有其他问题请 reopen。
