### ISSUE TITLE
如果在begin_op和end_op之间被kill掉会怎么办？

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#11]
比如之间有5个写请求，前四个正常执行，第五个在获得块时陷入睡眠，有可能被kill唤醒，如果此时被kill，我是应该保证在事务中的5个写请求都执行完毕，直到调用end_op，还是直接就exit掉进程就可以

**Comment by w568w** [comment]
很有意思的问题，我们分类讨论一下解决方案：

1. 最优雅的方案是**回滚**，即视此进程的事务为一次失败，撤销该事务对块缓存的影响。很遗憾，我们没有实现回滚的逻辑，所以在实际实现上会有比较大的困难（增加一个 `rollback_op`？）；
2. 另一个方案是**不管**，这个方案无疑是不好的：文件系统中将始终挂着这个无人结束的事务，任何新的 Checkpoint 都不会发生（因为 Checkpoint 必须等到所有事务都结束再进行！）；
3. 此外的方案就是**提交**。提交未必是一个好的方案，因为可能造成事务部分提交的问题，影响上层数据的一致性表示，而且在 exit 中提交或许会引发其它问题。你需要考虑一些别的问题：怎么追踪事务的开展情况？是否要把事务加入 PCB 中？
4. 或许还有第四个方案：**不允许 Kill**。将 Kill 延迟到该进程所有事务结束后再执行（为避免 Kill 不掉，可以再添加一个超时，在进程一段时间不提交后再强行 Kill？）。

**这个问题目前不是实验的要求部分之一，因为我们的进程不直接操作文件系统层（请等待下个关于 inode 实验就明白了），理应很罕见在一次操作期间被打断的情况，而且我们也不鼓励卷。**

但如果你感兴趣以任何方式解决（或者部分解决）该问题（即便不在本实验期间），无疑是一个好的创新点 :)
