### ISSUE TITLE
在运行内核态代码时会陷入时钟中断吗

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#13]
比如执行kalloc，cache_acquire函数时，会陷入时钟中断吗？

**Comment by w568w** [comment]
不会。

初始内核态：我们没有修改过中断位，默认不开启中断。

中断内核态：见 https://github.com/idlebo/OS-23Fall-FDU/issues/7#issuecomment-1779607812 ：

> ARMv8 在进入中断时会屏蔽中断上下文中的所有中断位（PSTATE 启用 DAIF），避免再受到任何异步中断触发，直到返回原上下文（即 eret），当然这也包括时钟中断。除非，你又手动开启了中断。

**Comment by SoftEgLi** [comment]
好的，谢谢
