### ISSUE TITLE
lab7 cache->acuqire后拿不到对应的block

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#14]
如图，我在测试代码中调用mock的acquire函数得到block，输出block的block_no，却发现是0。
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/d34d762d-8030-430a-933c-60e7ea0cc027)

**Comment by w568w** [comment]
我认为你拿到了正确的块。我们的 Mock 不太完善，只填充了 `data` 字段：

https://github.com/idlebo/OS-23Fall-FDU/blob/4abc17a829628a32fd142a8d10e3d39aee6a745e/src/fs/test/mock/cache.hpp#L55-L64

你可以认为其他字段都是缺省值（如 0）。当然，这不影响评测。

**Comment by SoftEgLi** [comment]
好的
