### ISSUE TITLE
在Mock的alloc中卡住

### ISSUE THREAD

**Issue by euReKa025** [idlebo/OS-23Fall-FDU#15]
经过调试，我发现在进行test_large_file()时，代码会卡在下图划红线处，并有以下报错信息，请问这是为什么？
<img width="890" alt="1" src="https://github.com/idlebo/OS-23Fall-FDU/assets/122709950/695b11c4-c241-4cb4-ba8e-247c16a56ef8">

**Comment by w568w** [comment]
具体是卡住了还是退出了？从你的图上似乎能看到报错退出了，但你的描述是「卡住了」。

如果是单纯的卡住，请检查你是否忘记释放一些块缓存的块上的锁。也可以用 GDB 连接到卡住的进程上查看线程堆栈（使用 `gdb -p <pid>`。

如果总是卡在一处（即 `i` 总是特定的值），可检查其他获取 `mblk[i].mutex` 和 `sblk[i].mutex` 的地方。

**Comment by euReKa025** [comment]
是我描述的问题，实际上是运行到这里时报错退出了。总是在test_large_file()的第一个写入循环中，写入最后一块时退出。

**Comment by w568w** [comment]
> 是我描述的问题，实际上是运行到这里时报错退出了

你能否打印 `mutex` 确认它们是有效的？这个报错看起来像是获取锁时出现了无效参数（例如，mutex 没有被初始化）。是否可能 Block 数组中的一些对象被你替换过？

----

根据 [`std::scoped_lock`](https://zh.cppreference.com/w/cpp/thread/scoped_lock/scoped_lock) 和 [`std::mutex::lock`](https://zh.cppreference.com/w/cpp/thread/mutex/lock)，唯一可能报错的情况是：

> 错误发生时抛出 [`std::system_error`](https://zh.cppreference.com/w/cpp/error/system_error)，包括底层操作系统阻止 `lock` 满足其规定的错误

而 `Invalid Argument` 对应到底层的 `EINVAL` 错误。[pthread_mutex_lock(3)](https://linux.die.net/man/3/pthread_mutex_lock) 揭示唯一可能报错的情况是：

> **EINVAL**
>   The value specified by mutex does not refer to an initialized mutex object.

**Comment by euReKa025** [comment]
问题已解决。原因是我在write函数中使用memcpy时未更新des变量的值。推测可能是改变了mutex的内容。
