### ISSUE TITLE
lab8 make qemu时报编译错误

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#16]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/33b354f8-3e1b-4222-9762-86405616297d)
请问该如何处理呢？

**Comment by singularity-s0** [comment]
可以把这行删了

**Comment by SoftEgLi** [comment]
取睡眠锁的时候需要定义checker，不太好删
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/542a41d0-be30-4d09-815a-1d352a0c28b2)

**Comment by singularity-s0** [comment]
`checker`并不是代码必须的部分，它只是一个方便减少错误的编译时检查。如果它给你带来了负面影响，你可以修改`unalertable_acquire_sleeplock`使它不需要`checker`

**Comment by singularity-s0** [comment]
但是这不应该是 Lab 8 的新问题，这个问题出现在`fs`模块，可以检查是否有忘记加锁/放锁的情况。如果确认没有这种情况，那么删掉`checker`即可

**Comment by SoftEgLi** [comment]
请问这个报错该怎么处理呢？
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/da79dff3-b6df-44f1-bf49-4cfbd6cb4d48)
