### ISSUE TITLE
inodes.root的类型问题

### ISSUE THREAD

**Issue by mzvltr** [idlebo/OS-23Fall-FDU#18]
inodes.root在注释中表示“/”的inode，应该是DIRECTORY类型，但打印结果显示是INVALID，为什么？如果不是DIRECTORY，如何从根目录开始查找目标路径的inode？
<img width="563" alt="inodeRoot2" src="https://github.com/idlebo/OS-23Fall-FDU/assets/104189449/ff20fe87-03b3-4a0d-8f0d-6b8ce06d292b">
<img width="482" alt="inodeRoot" src="https://github.com/idlebo/OS-23Fall-FDU/assets/104189449/78da0883-4a57-4539-a78e-7631623a7a2d">

**Comment by mzvltr** [comment]
是Directory类型，可看user目录下的mkfs程序，它用于创建文件系统（结果是一个root目录，底下有8个用户程序，形成二级目录）

**Comment by idlebo** [comment]
@w568w 你来看看呢（我感觉“/”不是 DIRECTORY 就是写错了，具体的 bug 在哪我也不知道，信息有点少）

**Comment by w568w** [comment]
上一个遇到此问题的同学的原因是「忘记加第二分区的起始 LBA 了，没有从逻辑块号转为真实块号」。

**Comment by mzvltr** [comment]
已解决，没有加起始LBA，device_read函数接收的block里面的no需要设置为真实块号
