### ISSUE TITLE
openat系统调用返回时出现broken pc?

### ISSUE THREAD

**Issue by mzvltr** [idlebo/OS-23Fall-FDU#19]
成功进入init的main函数后，在openat系统调用返回后（指return后进入trap return的eret之后出错）会出现broken pc的错误，而mknod系统调用不会出现。
错误不在openat内部，因为如果直接让openat返回也会出现相同的错误。
请问broken pc可能是哪些常见原因？

**Comment by w568w** [comment]
> broken pc可能是哪些常见原因？

直接原因是 `ec == ESR_EC_UNKNOWN` 且 `ir != 0b0`，表示是「未知原因错误」（如果 `ir == 0b0`，则表示这是一次普通外设中断而非异常引发的中断）。

此时不能依靠 esr 来判断异常原因，只能输出 elr 和 far、sp 等相关寄存器来判断。这些寄存器的作用请自查手册。

实际上，在我们实验中出现此错误组合比较常见的原因是：试图跳转到完全不存在的指令位置，例如 `pc` 被设为一个不存在的地址值。这种情况出现时，你也需要检查 pc 的值。

**Comment by mzvltr** [comment]
pc被设为不存在的地址，在返回的时候出错需要检查lr寄存器（x30），该寄存器需要保存在UserContext中
