### ISSUE TITLE
About checker mechanism

### ISSUE THREAD

**Issue by Boreas618** [idlebo/OS-23Fall-FDU#2]
我注意到该项目中存在一个checker机制，例如：

```c
#define increment_rc(checker, rc) checker_begin_ctx_before_call(checker, _increment_rc, rc)
```

该宏定义包装了`_increment_rc`，似乎在调用`_increment_rc`前进行了一些上下文检查。但是在项目中的其他的模块中，模版代码直接调用了`_increment_rc`，而非`increment_rc`包装的`_increment_rc`，如：

```c
_increment_rc(&alloc_page_cnt);
```

我的问题是：

* 能否详细解释checker机制？
* 跨过`increment_rc`直接调用其包装的`_increment_rc`在代码规范上是否合适？
> 按照我的理解，checker似乎不是必要的（因为也有直接调用`_increment_rc`的情况），那么是否可以将启用checker作为`increment_rc`原语的options之一？

**Comment by w568w** [comment]
> 能否详细解释 checker 机制？

checker 的实现见 <https://github.com/idlebo/OS-23Fall-FDU/blob/lab2/src/common/checker.h>。

简单来说：

1. `setup_checker` 宏声明一个 `int` 类型的变量，其名称为 `__chkcounter_##id`。该变量被分配了 [`__attribute__((cleanup))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Variable-Attributes.html#index-cleanup-variable-attribute)，被配置为在离开变量作用域时执行函数 `__checker_check`；
2. 强制内联函数 `__checker_check` 检查 `__chkcounter_##id` 的值是否为 0，不为 0 时执行函数 `__checker_fail`；
3. `__checker_fail` 具有属性 [`__attribute__((error))`](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-error-function-attribute)，这使该函数会被执行时，将在编译期报错。

藉由语言分析的功能，一些 IDE 和编译器的组合可以在编译期（甚至静态检查期）确定是否报错，从而保证最终目的：**`checker_begin_ctx` 和 `checker_end_ctx` 被配对执行**。

> 跨过 `increment_rc` 直接调用其包装的 `_increment_rc` 在代码规范上是否合适？

**通常不合适**，这取决于语境。例如在这里，**因为我们不需要保证在同一作用域下两者被配对执行，所以是合适的**。

p.s. 在本实验课程的评判中，一般不会因此影响分数。

**Comment by JingYiJun** [comment]
[src/common/rc.h](https://github.com/idlebo/OS-23Fall-FDU/blob/5a1b4f8364e41823c0f38b9cf89f632b2ae5968e/src/common/rc.h#L16C24-L16C24) 声明宏使用的 `checker_begin_ctx` 和在 [src/common/checker.h](https://github.com/idlebo/OS-23Fall-FDU/blob/5a1b4f8364e41823c0f38b9cf89f632b2ae5968e/src/common/checker.h#L9C14-L9C14) 定义的 `checker_begin_ctx` 宏参数要求不一样。

使用这个函数会导致IDE的分析器报错：宏调用的参数过多。

编译也不过。

<img width="558" alt="image" src="https://github.com/idlebo/OS-23Fall-FDU/assets/19527729/f0f95700-0f34-4ca5-b600-554bcaa116c4">

**Comment by w568w** [comment]
cc @idlebo

**Comment by idlebo** [comment]
@Fanaesar 还有问题😢

**Comment by Fanaesar** [comment]
@idlebo @JingYiJun 现在应该没有问题了，我测过了

**Comment by Fanaesar** [comment]
checker的作用是为了防止大家出现使用了锁但是没有放掉的情况，确实是可以不去使用的。但是这样的话需要格外小心锁的使用

**Comment by w568w** [comment]
如果还有其他问题，请 reopen。
