### ISSUE TITLE
lab-finished分支下，sblock无法读取，但在lab8下正常，请问可能的原因？

### ISSUE THREAD

**Issue by Zeus-Xu** [idlebo/OS-23Fall-FDU#20]
如图lab-finished分支下，sblock无法读取，但在lab8下正常，请问可能的原因？已在block_device.c sd_read sd_write加入LBA。
lab8
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/60375206/c950e839-30c6-4f92-91ca-3452af78e650)
lab-finished
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/60375206/a766feb7-4017-4d56-a167-68f76d90b165)
图中panic的原因是sblock num_inodes为0导致root inode 的编号1>sblock.num_inodes引发

**Comment by w568w** [comment]
> 已在block_device.c sd_read sd_write加入LBA

所以 sd_read(0) 还能读到 MBR 吗？或者你现在使用别的方法读取 MBR？

**编辑**：你看起来没有「读取」MBR 而是直接**硬编码**了第二个分区的起始位置。**这在实际的内核中是绝对错误的。**

你的操作系统不应该假定硬盘上的分区是从哪个位置开始的，而应该利用 MBR。这方便于调试，但请不要「刻舟求剑」式地「刻 blockno 求分区」。

**Comment by idlebo** [comment]
可以看看 lab5 里面写的 sd_intr 有没有发生调用，如果没有的话，可能是系统中没有进程响应 sd 中断

**Comment by Zeus-Xu** [comment]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/60375206/17a8e70e-9436-4eee-82d3-0f2636ceb2e4)
可以读到

> > 已在block_device.c sd_read sd_write加入LBA
> 
> 所以 sd_read(0) 还能读到 MBR 吗？或者你现在使用别的方法读取 MBR？
> 
> **编辑**：你看起来没有「读取」MBR 而是直接**硬编码**了第二个分区的起始位置。**这在实际的内核中是绝对错误的。**
> 
> 你的操作系统不应该假定硬盘上的分区是从哪个位置开始的，而应该利用 MBR。这方便于调试，但请不要「刻舟求剑」式地「刻 blockno 求分区」。

**Comment by Zeus-Xu** [comment]
> 可以看看 lab5 里面写的 sd_intr 有没有发生调用，如果没有的话，可能是系统中没有进程响应 sd 中断
应该有调用
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/60375206/d53fb189-f534-4817-9541-ff8a894ab799)

**Comment by Zeus-Xu** [comment]
> > 已在block_device.c sd_read sd_write加入LBA
> 
> 所以 sd_read(0) 还能读到 MBR 吗？或者你现在使用别的方法读取 MBR？
> 
> **编辑**：你看起来没有「读取」MBR 而是直接**硬编码**了第二个分区的起始位置。**这在实际的内核中是绝对错误的。**
> 
> 你的操作系统不应该假定硬盘上的分区是从哪个位置开始的，而应该利用 MBR。这方便于调试，但请不要「刻舟求剑」式地「刻 blockno 求分区」。

sd_read(0)的结果
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/60375206/ca460590-45db-4025-86bd-2ffb1d08da58)

**编辑**：仅将init_block_device()中sd_read(1, sblock_data)改为sd_read(0, sblock_data)

**Comment by w568w** [comment]
> sd_read(0)的结果
> 
> 仅将init_block_device()中sd_read(1, sblock_data)改为sd_read(0, sblock_data)

我没有明白你的意思。这里除了 `LBA` 和 `Number` 两行以外都和 MBR 没有关系，你想展示什么？改成 `sd_read(0)` 之后可以读超级块了？那问题不是解决了？那原来（指 lab8）为什么 `sd_read(1)` 可以正常运行？

此外，我更希望你能解决一下 `BLOCKNO_OFFSET` 这个宏的问题。我们可从来没有保证过第二个分区就在 `0x20800` 处……这是不良的编码陋习。

**Comment by Zeus-Xu** [comment]
> > sd_read(0)的结果
> > 仅将init_block_device()中sd_read(1, sblock_data)改为sd_read(0, sblock_data)
> 
> 我没有明白你的意思。这里除了 `LBA` 和 `Number` 两行以外都和 MBR 没有关系，你想展示什么？改成 `sd_read(0)` 之后可以读超级块了？那问题不是解决了？那原来（指 lab8）为什么 `sd_read(1)` 可以正常运行？
> 
> 相比于此，我更希望你能解决一下 `BLOCKNO_OFFSET` 这个宏的问题。我们可从来没有保证过第二个分区就在 `0x20800` 处……

好的，我稍后解决宏的问题。我的意思是想询问从lab8变到lab-finished，读超级块需要改为sd_read(0)可能的原因。

**Comment by w568w** [comment]
> 我的意思是想询问从 lab8 变到 lab-finished，读超级块需要改为 sd_read (0) 可能的原因。

我没有说「读 SuperBlock 需要改为 sd_read (0)」，这里改完后「碰巧」能运行，说明问题可能正是你硬编码地址带来的。请在读写块设备时严格遵循我们在 Lab5、6 时说明的文档。

**Comment by Zeus-Xu** [comment]
> > 我的意思是想询问从 lab8 变到 lab-finished，读超级块需要改为 sd_read (0) 可能的原因。
> 
> 我没有说「读 SuperBlock 需要改为 sd_read (0)」，这里改完后「碰巧」能运行，说明问题可能正是你硬编码地址带来的。请在读写块设备时严格遵循我们在 Lab5、6 时说明的文档。

已经修改为直接从sd_init中解析mbr得到的地址。结果未变，仍然需要sd_read(0)。请问还有什么可能的原因。

**Comment by w568w** [comment]
> 仍然需要 sd_read (0)。请问还有什么可能的原因。

请阅读文档。
