### ISSUE TITLE
lab-finished中，调用bcache的commit时进入el1_spx函数，请问这个函数是什么

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#21]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/6898ca6b-fc07-4edd-9ce3-bec2555d319a)
从调用堆栈可知在进入了commit函数后立即进入el1_spx函数

**Comment by w568w** [comment]
请阅读 <https://github.com/idlebo/OS-23Fall-FDU/blob/lab-finished/doc/trap.explained.md>。
