### ISSUE TITLE
pdfault_handler出现无法解决的异常

### ISSUE THREAD

**Issue by mzvltr** [idlebo/OS-23Fall-FDU#22]
pgfault_handler捕获intruction abort - translation fault，根据地址可以找到section与表项，且检验pte_flag是只读的，被程序认定为Copy on write，这并不合理。

详细说，这里出现一些和假设不符的情况。比如：
我目前理解的translation fault就是页表找不到表项导致翻译失败。data abort / instruction abort - translation fault触发，但是通过get_pte能拿到有效的表项，且所属的section存在，这和假设矛盾。

在我的实现中，由于esr只是用于参考，真正判断错误类型的还是section是否存在、pte是否存在以及pte flag，所以上面的这种情况会被归于copy on write，即报错是因为写入只读页。
但esr显示它是intruction abort，不应该是写操作导致的。

**Comment by singularity-s0** [comment]
这可能由很多原因导致，例如页表flags不正确、设置了错误的ttbr0、TLB与页表不同步等（但最后这种情况不会发生，因为TLB不会缓存translation fault的地址）。

建议首先定位是哪行代码触发了这个问题。不出意外的话，instruction abort意味着用户程序正在试图执行该位置的指令。你是否使用了demand paging技术？你是如何将该页面map给用户程序的？用户程序能否读取该位置的数据？

**Comment by w568w** [comment]
如果有后续活动，请重新打开。
