### ISSUE TITLE
没法正常进boot，在do_init进行idleinit的时候pc到未定义段去了

### ISSUE THREAD

**Issue by yimdx** [idlebo/OS-23Fall-FDU#24]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/2a2129b4-7254-4de9-a230-1eccd40a7cb1)

**Comment by idlebo** [comment]
这个地址看起来是在进行 init 的时候遇到了异常，可以排查一下定义了哪些 init 函数，这些函数中是否会引发异常

**Comment by yimdx** [comment]
排查过了，idle_init出的问题，这里kalloc的size_input莫名其妙值变了，不是很理解
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/316fa2b4-bb97-435d-b9b9-8840891ea9e2)

**Comment by yimdx** [comment]
已解决！oftable设置错了太大了
