### ISSUE TITLE
疑似sblock无法初始化

### ISSUE THREAD

**Issue by euReKa025** [idlebo/OS-23Fall-FDU#25]
我在启用单核调试后，进行到init_bcache时调用read_header(),具体来说是device->read(sblock->log_start, (u8 *)&header);
之后进入sd_start产生如下报错：
<img width="889" alt="屏幕截图 2024-01-26 173310" src="https://github.com/idlebo/OS-23Fall-FDU/assets/122709950/afb942b2-4bdd-48a0-82e4-a47dfbc8b718">
观察变量发现，存储super_block的sblock_data应该未赋值，如下图所示：
<img width="1031" alt="屏幕截图 2024-01-26 174014" src="https://github.com/idlebo/OS-23Fall-FDU/assets/122709950/993d9648-1ba1-442f-acec-8c4786a26d5f">
猜测这是产生上述报错的原因。
但是我无法找到一个合适的地方对sblock进行赋值，这与cache测试时不同，请问应该怎么做？

**Comment by zywgngc** [comment]
同问！我也遇到了这个问题

**Comment by w568w** [comment]
> 我无法找到一个合适的地方对sblock进行赋值

https://github.com/idlebo/OS-23Fall-FDU/blob/351bafa45bbdfefc9cee7933ca3ec2e3368653e0/src/fs/block_device.c#L45-L46

**Comment by euReKa025** [comment]
好的，我之前没有发现这里有TODO。但是当我补充完整之后，进入sdInit()时，调用了sdGetBaseClock()函数(sddef.h 1151行)，进而调用 mbox_get_clock_rate函数。在这个函数中，创建buf时，我注意到buf的地址并不是16字节对齐的。如下图所示：
<img width="1169" alt="屏幕截图 2024-01-26 183137" src="https://github.com/idlebo/OS-23Fall-FDU/assets/122709950/87f0c514-963d-4b61-b356-4ffb1c66389e">
这导致出现了以下报错（buf未对齐），请问这该怎么解决？
<img width="953" alt="屏幕截图 2024-01-26 184030" src="https://github.com/idlebo/OS-23Fall-FDU/assets/122709950/2ed25d2d-1765-40e6-a013-9ca0c1be3454">
主要是我自己分配内存应该都对齐了，不清楚这是为什么。而且前面的__attribute__((aligned(16)))已经要求强制对齐了

**Comment by w568w** [comment]
> 调用 mbox_get_clock_rate 函数。在这个函数中，创建 buf 时，我注意到 buf 的地址并不是 16 字节对齐的。

你的 Lab5 通过测试了吗？对于这种情况我能想到可能的解释是：

1. 你的 GCC 版本太旧以至于不支持栈对齐。在 2011 年之前，GCC 4.4 及更低版本中，[栈变量的对齐属性会被简单地忽略](https://gcc.gnu.org/legacy-ml/gcc-patches/2010-10/msg00060.html)；
2. GCC 以一种不太可靠的方式实现了栈对齐，以至于你内核中的一些内存布局错误影响了其行为。

快速（但不追根究底）的解决方法包括：

1. 自己分配内存（例如使用 `kalloc`）；
2. 使用静态变量：

    ```c
    static __attribute__((aligned(16))) u32 buf[] = {36, 0, MBOX_TAG_GET_CLOCK_RATE, 8, 0, 1, 0, MBOX_TAG_END};
    ```
3. 直接让该函数返回非 `-1` 值。**在目前的玩具驱动实现中，我们并不依赖它返回的结果，你可以用任意值代替（例如 0）。**

**Comment by euReKa025** [comment]
lab5通过了。目前使用方法2解决了这一问题
