### ISSUE TITLE
怎么进入用户态

### ISSUE THREAD

**Issue by yimdx** [idlebo/OS-23Fall-FDU#26]
请问可能是什么原因导致我的elr_el0不对？应该是0xffff000000086000，但是没有进trap_return 没有进icode而是到了0xffff00000008e07c
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/67c6e0ce-5e56-4bd0-b323-115ac293d9ac)

**Comment by idlebo** [comment]
左边 58 行直接把 elr 设成 0 试一下呢

**Comment by yimdx** [comment]
设成0也不行，不过这里本来就是0。如果我没有理解错的话，应该是trap_return里eret返回到icode处，这里elr_el0应该经过页表转换到ka开始运行，但是这里不可以，页表逻辑应该没有太大问题，是可以通过page_fault和userproc这两个之前的测试的。这里的问题看上去是0xffff00000008e07c不在合法section中，但实际上trap_return里面eret没有返回到0xffff000000086000即icode处。
我又debug了一下，这边eret时这个elr = 0是不是对的，那应该是页表出的问题？
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/54b34cc6-88c1-4477-8f25-634f870533ee)

**Comment by idlebo** [comment]
emm，这里你试过和 userproc 中一样的写法吗，如果没有的话可以试试（如果用 get_pte 可以完成页表配置的话，说明可能是你的 vmmap 有问题）

**Comment by yimdx** [comment]
用getpte确实解决了（哭），但是我这里vmmap写的有啥问题吗（求问
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/980258e1-ef7c-48a6-b6d8-66af60503063)

**Comment by idlebo** [comment]
懵了，我也没看出来哪里有问题

**Comment by yimdx** [comment]
啊这好吧，谢谢助教
