### ISSUE TITLE
execve出现pagefault

### ISSUE THREAD

**Issue by yimdx** [idlebo/OS-23Fall-FDU#27]
这里直接在exevce中访问0x40014c不会page fault但是elr_el1好像就会触发pagefault，这可能是什么原因？
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/e63ac032-9522-492e-936f-1441b869e6fe)

**Comment by yimdx** [comment]
从exevce能够映射来看好像没有配错页表

**Comment by yimdx** [comment]
用gdb调了一下更奇怪了，明明应该没有进init，栈里面却出现了console
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/1b58f08b-8481-4cac-a649-6fe5adfedd68)

**Comment by w568w** [comment]
> 直接在 exevce 中访问 0x40014c

什么叫「直接访问」，在 gdb 里用打印命令访问？

从你的代码里我看到 `ucontext->elr == 0x40014c`，但我没有看到直接访问该内存地址的代码逻辑。

> 但是 elr_el1 好像就会触发 pagefault

同上，请详细解释一下，不要打谜语：什么是「elr_el1 会触发 pagefault」？`ucontext->elr` 不就是 `0x40014c` 吗？

> 明明应该没有进 init，栈里面却出现了 console

没有看出你在调试什么地方的断点。仅凭这张图我能给出的解释是 `console_intr` 在初始化阶段就已经注册到中断处理，后续只要在终端（即串口界面）中输入字符，就可能触发串口中断，这和是否进入 `init` 应该没有关系。

**Comment by yimdx** [comment]
execve里面用get_pte可以访问虚址
eret时触发了iabort- lv0 translation fault
我直接设置ttbr0好像解决了这个问题

**Comment by w568w** [comment]
> execve里面用get_pte可以访问虚址

这和「访问 0x40014c」完全不是一回事。你只是在获取当前进程的用户空间页表下 `0x40014c` 地址对应的页表项。

>  eret时触发了iabort- lv0 translation fault

这和「触发 pagefault」也不是一回事。IABORT 是指令异常，而 LV0 translation fault 意味着在翻译时访问第 0 级页表就出错了。

>  我直接设置ttbr0好像解决了这个问题

我可以理解为问题解决了？关闭 issue。

**Comment by yimdx** [comment]
发现是attach同时在trap中又设置了一遍ttbr0覆写导致的
