### ISSUE TITLE
请问该怎么进入shell？

### ISSUE THREAD

**Issue by yimdx** [idlebo/OS-23Fall-FDU#28]
![b0e502ad13b6d9ed9a78dcc1983c718](https://github.com/idlebo/OS-23Fall-FDU/assets/100195831/3e873f1c-35c0-4908-9188-3e76fd0ea553)
看上去这个一直在fork - execve(sh)，这样是不是不正确？应该是什么样子的？还有printf出来的东西会显示在哪里？我在哪能找到shell? 看上去在init里面是进了第二个if，但是fork返回的child_pid不为0

**Comment by w568w** [comment]
> 这样是不是不正确

是。

> 应该是什么样子的?

fork 后产生一个 sh 进程，保留原进程。

> printf出来的东西会显示在哪里？

通过 inode 层转接 console 驱动，最终显示在终端里。

> 我在哪能找到shell? 

shell 可以代指：

1. 实验文档的 Shell 一节；
2. Shell 可执行文件；
3. Shell 程序运行后输出的内容；
4. 服务器的 Shell。

说清楚你想要什么。

> 看上去在init里面是进了第二个if，但是fork返回的child_pid不为0

仅凭你的一张残缺的截图，无法判断怎么会在 `pid != 0` 时进入第二个 if。

---

**请务必说明清楚，一张不全的、没有任何前因后果说明的调试截图 + 指代用词模糊不清、过分简略且不给出上下文代码信息的提问，无益于你的问题的解决。**

**Comment by yimdx** [comment]
不是很清楚user/init的逻辑。我没有办法判断我的问题在哪里。
首先在open(console)+dup之后，在fork之前是否就已经通过inode转接到了console驱动，而我应该看到printf输出的内容？如果是那么是不是说明我的console函数实现不正确？

**Comment by yimdx** [comment]
另外请问是如何转接的，open("console")这一部分我认为应该无关console read等函数，所以可能是哪里出的问题？我该如何debug？

**Comment by yimdx** [comment]
我明白了，inode.read 和inode.write里需要调用console_read和console_write,后面的问题我再研究一下

**Comment by yimdx** [comment]
请问user/init里面创建console，之后可以用openat打开(找的到path对应的inode)， 但是fork后切换进程之后就无法再找到对应的inode了，（inodes.lookup返回是0）可能是什么原因？ 已经检查过是相同的path和cwd(root)。
