### ISSUE TITLE
inodes.lookup

### ISSUE THREAD

**Issue by yimdx** [idlebo/OS-23Fall-FDU#29]
请问user/init里面创建console，之后可以用openat打开(找的到path对应的inode)， 但是fork后切换进程之后就无法再找到对应的inode了，（inodes.lookup返回是0）可能是什么原因？ 已经检查过是相同的path和cwd(root)。

**Comment by yimdx** [comment]
补充说明：在init进程中，filename=console在mknod之后可以在inodes.lookup(root)中找到，并且检查过在bcache commit之后也能找到（从而openat），但是切换到sh进程后，无法在inodes.lookup(root)中找到，检查过path 和 cwd都和init进程保持一致，而且inode(root)的numbytes参数和能找到console的时候保持一致

**Comment by w568w** [comment]
> 在 init 进程中，filename=console 在 mknod 之后可以在 inodes.lookup (root) 中找到……但是切换到 sh 进程后，无法在 inodes.lookup (root) 中找到

两次 lookup 中，目录项的内容有区别吗？

**Comment by yimdx** [comment]
已解决 没有回写
我只在sd_read里做了逻辑块偏移，sd write忘了（呜呜
