### ISSUE TITLE
内存地址对齐

### ISSUE THREAD

**Issue by Boreas618** [idlebo/OS-23Fall-FDU#3]
> 对于常见的内存需求而言，完整的物理页还是太大了。就如我们在C中使用过的malloc和free一样，内存分配器动态分配若干物理页，将其切分为程序分配指定大小的内存块，并回收程序释放的内存块用于再分配。分配的内存块地址必须与大小对齐，即：如果需要分配的内存大小是 2 的倍数，则地址也要是 2 的倍数；如果大小是 4 的倍数，地址也要是 4 的倍数；如果大小是 8 的倍数，则地址也要是 8 的倍数。和内存页的分配不同，一般的分配器不需要 16 字节以上的对齐，如大小是 16 的倍数，则地址只需是 8 的倍数。（为什么？）

为什么有这样的对齐要求呢（因为我现在还没有开始做这个对齐，也没有想到为什么要做对齐）？以及这样的对齐要求是否包含在测试用例里？

**Comment by w568w** [comment]
> 为什么有这样的对齐要求呢（因为我现在还没有开始做这个对齐，也没有想到为什么要做对齐）？

这是思考题的一部分。让我们暂时不揭晓答案 :)

提示包括：处理器缓存；内存布局；[对齐要求](https://zh.cppreference.com/w/c/language/_Alignas)。

> 这样的对齐要求是否包含在测试用例里？

[是的](https://github.com/idlebo/OS-23Fall-FDU/blob/b40d3757c3fe5f3b737001d435b6cf1a7142d40a/src/test/allocator.c#L85-L90)。

**Comment by Boreas618** [comment]
这里的wrong是指内存对齐错误吗？
 
(测试用例里的变量命名有点晦涩)
<img width="478" alt="Screenshot 2023-09-25 at 12 24 41 AM" src="https://github.com/idlebo/OS-23Fall-FDU/assets/98612013/e6d6e0c2-24a6-48dc-9306-f674321eb46d">

**Comment by idlebo** [comment]
这里不是检测内存对齐，这里检测的是之前写入块中的内容是否被污染
