### ISSUE TITLE
UserContext中为何要保存sp指针

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#4]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/269997c9-43c6-410c-91ca-75ef0fa866d3)

![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/2786f0e7-d92b-479c-bd85-4c16fdc57728)
ucontext作为指针，其值是否是栈指针值？如果是的话，sp寄存器似乎没有必要放在UserContext结构中。

**Comment by idlebo** [comment]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/95092670/345575a1-9877-40ee-8dd1-6877facfbb09)
其值不是栈指针（这个图是 API reference 里面的截图

**Comment by SoftEgLi** [comment]
那在trap.S中调用trap_global_handler的时候，传入的函数参数值（context）该是什么呢

**Comment by w568w** [comment]
> ucontext作为指针，其值是否是栈指针值？

如果你的意思是指针本身的值，答案是**是的**。确切地说，是当前栈的栈顶指针（例如我们的中断处理者是 EL1，那么是 `SP_EL1`）。这是因为我们利用栈来保存了其他寄存器的值。

> sp寄存器似乎没有必要放在UserContext结构中。

三件事：

1. 正如文档介绍的，**ARMv8 中不存在一个单独的 SP 寄存器：每一个 EL 都有一个自己的 SP 寄存器**。既然已经知道 `ucontext == SP_EL1`，那我们保存的自然是 `SP_EL0` 寄存器的值；
2. 我们必须保存所有寄存器的值，不是因为它们无法得到（如果要说 `SP_EL0` 可以读出来所以就不用存，那 x0~x31 寄存器大部分其实在 `trap_global_handler()` 开头都可以用内联汇编指令读出来，那是不是都不用存？），而是因为它们代表了用户态的运行状态。如果你不确定一个寄存器是否要存，那么判断的原则是：**如果在用户程序运行中给这个寄存器写入一个垃圾值，该用户程序是否还能正常运行？** `SP_EL0` 显然是在这个范畴中的；
3. `UserContext` 不是一个只读的结构体，我们可以改变它的值从而控制恢复后的行为，就像对 `KernelContext` 所做的一样。例如，假如我们的内核需要动态改变用户空间的栈指针位置的功能，`SP_EL0` 是必须预留的一个可写入的字段。

**Comment by SoftEgLi** [comment]
明白了，谢谢助教老师
