### ISSUE TITLE
is_unused

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#5]
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/cf8b48b9-b706-4565-999d-eaff3a6fe8d5)
这里似乎应该是UNUSED

**Comment by w568w** [comment]
看起来是[和去年一样的错误代码](https://github.com/FDUCSLG/OS-2022Fall-Fudan/blob/07559de95e55270e540577b47c73980fdb8dd1da/src/kernel/sched.c#L38-L54)。

cc @idlebo

**Comment by idlebo** [comment]
OK，已经改正
