### ISSUE TITLE
有一个小概率会发生的死锁问题

### ISSUE THREAD

**Issue by timwang1220** [idlebo/OS-23Fall-FDU#7]
当获得了调度锁的进程进入trap之后，它需要exit，此时需要使用进程树锁；
但是有概率其他cpu在执行其他进程的kill函数，并已经获得了进程树锁，此时它需要activate_proc，需要使用调度锁
此时就会导致死锁问题的出现
有点不知道应该怎么解决这个死锁问题，是应该在获得调度锁时禁用trap吗？（但感觉好像不太合理，程序好像也没法跑通

**Comment by idlebo** [comment]
同学，你在测试中遇到了上述的死锁情况吗（大部分情况下，我们的内核代码很少会发生 trap：首先对于同步的异常，目前我们的实验应该是不会出现内核代码主动出发同步异常的情况；对于异步的异常（也就是中断），目前我们只在特定的部分开启了中断的响应（仅在 `arch_with_trap` 包裹的代码段中允许响应中断），这是因为在持有自旋锁的过程中是不应该响应中断的（否则可能造成严重的效率地下的情况，因为响应中断所需的时间一般比较长），而我们的内核代码频繁用到自旋锁，所以我们的内核代码干脆关掉了中断，仅在一小段代码中开启中断响应。），因此我不确定你提到的“当获得了调度锁的进程进入trap”这一情况是否存在。

**Comment by timwang1220** [comment]
似乎确实是发生了 发生的概率不大 一般只有30-50次测试才能发生一次 因此很难debug 我只能在发生的时候查看当前的情况
我用lockid和lockcpuid记录了sched_lock的获得情况
在下面的图片里似乎就是cpu0运行的process19抢占了sched_lock，然后现在正在执行trap里的exit指令
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/96069313/5e6341c6-ffb0-4d5c-b4bb-f76d3dfe4b9b)
会不会可能是因为时间中断出现了嵌套 导致这个进程前面时间中断抢占了调度锁还未来得及释放 然后后来中断进入trap出现了“当获得了调度锁的进程进入trap”的情况
然后我看到了reference里提到了这个问题
![94820f89a57411a08b7a1dcdeb87701](https://github.com/idlebo/OS-23Fall-FDU/assets/96069313/4208db7f-164c-4860-8ec6-e3a82e2f862a)
但是好像直接使用原有的arch_enable_trap和arch_disable_trap是不行的（是否是因为这只是在操作内核的trap开关，并没有改变用户的接受中断位），之后我尝试在处理handler和handler之后尝试使用daifset和daifctl打开关闭中断，不过问题好像还是会出现，不过好似概率更低了（？
我想知道这样的问题是不是中断嵌套带来的，我们应当如何操作打开关闭中断呢

**Comment by idlebo** [comment]
emm，这种情况可能概率确实很低（我在我的代码上测了几十次也没能遇到死锁），但我觉得你分析的不太对，应该不至于两个时钟中断连着出现（除非你把间隔设置为纳秒级别）。
至于这个死锁的解决方法，我认为可以在 kill 函数中，找到要 kill 的进程后就放掉调度树的锁，然后再去做 activate_proc ，这样应该可以解决你的死锁问题（这样的语义上也是合理的）。或者，我们在 lab4 的文档中也提到 kill 这里其实如果不加锁也没啥事，你也可以在这里不给进程树加锁。
另外，需要说明，你提到的在用户态关闭中断的想法是危险的，因为时钟中断是操作系统获取控制权的手段，如果你在用户态关掉了中断，就相当于将整个 CPU 交给某个进程（其他进程将无法执行），操作系统不应该做出这样的事。

**Comment by timwang1220** [comment]
感谢助教！确实不应该想着在用户态关闭中断，助教的方法也是有效的，我也尽可能避免了在获得进程树锁情况下再去获得调度锁，这样测试下来概率又降低了很多（大约1/200），但我认为这似乎并没法完全解决问题，因为关键问题还是在调度锁不在进程树锁，还是会出现死锁的问题。因为如果进入trap有调度锁没有释放，trap的调度锁（exit函数还是需要调度锁）还是无法获得。我认为根本问题是在进入trap时带着调度锁，而这如果说内核态是不会在得到调度锁的情况下遭遇trap，那感觉只能是接连两次trap所带来的，我尝试调大时间片好像也无法根本解决问题（会不会是调度锁粒度过大导致的问题？

**Comment by w568w** [comment]
补充一些。

> 会不会可能是因为时间中断出现了嵌套
> 
> 处理 handler 和 handler 之后尝试使用 daifset 和 daifctl 打开关闭中断

理应不存在这样的情况。ARMv8 在进入中断时会屏蔽中断上下文中的所有中断位（`PSTATE` 启用 DAIF），避免再受到任何异步中断触发，直到返回原上下文（即 `eret`），当然这也包括时钟中断。除非，你又手动开启了中断。

> 后来中断进入 trap 出现了 “当获得了调度锁的进程进入 trap” 的情况
>
> 我认为根本问题是在进入 trap 时带着调度锁

这听起来是不合理的也是不应该出现的。再仔细检查你的代码，尤其是获得调度器锁后的部分。**进入用户态之前必须释放锁、必须保证未开启中断（当然，IDLE 进程除外）。**（如果不方便静态分析，那么在所有边界守卫处动态地做检测然后 PANIC。）

> 直接使用原有的 arch_enable_trap 和 arch_disable_trap 是不行的

什么是不行的？

> 是否是因为这只是在操作内核的 trap 开关，并没有改变用户的接受中断位

我猜你的意思是「操作的是 EL1 的中断控制位」，答案是肯定的。**我们从未改变过 EL0 的中断控制位，你也不应该改变它们。用户态任何时刻都要接受所有中断。**

> 感觉只能是接连两次 trap 所带来的

不清楚你的代码是如何编写的，提供一个检测思路：不仅储存最近一次上锁的 CPUID，还储存最近一次上锁的位置（可以编个号，例如：0,1,2...）。在 trap 入口函数处检查调度器锁是否被当前 CPU 持有，如果持有立刻 PANIC，打印上次上锁的位置，或者在判断成功的分支上触发断点。

---

从你的描述来看，这是一个很有意思的低概率事件。如果重大问题在我们助教的代码这边，我们很乐意和你一起探究原因。

**Comment by timwang1220** [comment]
观察我上面的截图，我发现进程堆栈里有许多trap_entry，感觉这似乎是不正常的，但是理论上来说，内核态的trap似乎并不是打开的，也就是不会出现在trap时进入trap的情况
我于是按照issue8里同学的描述尝试在trap_entry中自己手动关闭中断如图，这个时候我再在kill阶段的时候查看堆栈，发现堆栈不会出现像上述截图一样的大量trap_entry的问题
![1698300212376](https://github.com/idlebo/OS-23Fall-FDU/assets/96069313/b642cd15-b6c0-43b3-a2a1-33d4613089f6)
此时我在trap_entry中的ASSERT判断进程是否带有调度锁进入也不会触发，死锁的问题好像也不会再出现（大约测试了3000+
所以为什么我在trap.S里手动关闭这个中断就解决了这个问题，而之前调用arch_disable_trap()或是说依靠自带的trap机制（什么都不做）就会在kill阶段死锁查看堆栈时有大量trap_entry？

**Comment by w568w** [comment]
> 我于是按照issue8里同学的描述尝试在trap_entry中自己手动关闭中断

如果修改了 DAIF 位就可以解决该问题，那么你能否打印出进入中断时 DAIF 的原始值？我很好奇为什么 DAIF 没有设置为掩蔽。

> 为什么我在trap.S里手动关闭这个中断就解决了这个问题，而之前调用arch_disable_trap()

`_arch_disable_trap` 的逻辑并不是助教的机密―我想你有能力自己阅读它的实现，不需要我们再说明。:)


---

附 *Programmer's Guide for ARMv8-A* 文档中有关异常处理部分的中文翻译：

> 当处理器接受一个异常到 AArch64 执行状态时，所有的 PSTATE 中断掩码都会自动设置。这意味着后续的异常将被禁用。如果软件要支持异常嵌套，例如，允许高优先级的中断去打断对低优先级源的处理，那么软件需要显式地重新启用中断。

**Comment by w568w** [comment]
太久没有回复，先关闭。如果有回应请 Reopen。
