### ISSUE TITLE
如何在trap_return的时候进行时钟中断的计时

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#8]
当我的时间片比较小，大概小于30ms的时候，有可能发生trap后连着trap的情况。我尝试在trap_entry中把daif寄存器给关掉，在trap_return函数中开启，结果是在开启的一瞬间就进入时钟中断了。在trap_return中重新设时钟值也不可行。
![image](https://github.com/idlebo/OS-23Fall-FDU/assets/106418587/9df962ff-de5b-4ed4-9133-94ee5d069a3a)
有没有什么办法，可以让时钟中断的计时在trap_return之后（或者在trap_return发生时）才开始

**Comment by idlebo** [comment]
没太看懂你的问题，你说的 "trap后连着trap" 是导致什么错误了吗（如果是的话，详细说明你遇到的错误会更好），因为我不知道你的错误，所以也不太理解你的解决方法，我是不知道有方法可以时钟中断的计时在trap_return之后开始。

**Comment by SoftEgLi** [comment]
"trap后连着trap"的意思是在trap_return函数里，当我将中断打开的时候（把daif寄存器的值设为0，也就是截图中倒数第二行代码），由于中断处理程序花费的时间超过定时器的elapse，立刻陷入了时钟中断。当这个时钟中断处理完进入trap_return后，在中断打开时又立刻触发了定时器，如此循环，这导致后面的eret指令没法执行，也就意味着没法跑实际的用户代码。我想问有没有办法可以延缓时钟中断的触发，使得只有运行用户代码的时候才开始进行中断的计时（比如我把elapse设为50，那么只有用户态运行50ms后才会触发时钟中断）

**Comment by idlebo** [comment]
你代码截图中的倒数第三行，似乎是向 `cntp_tval_el0` 寄存器中写入 0，这会导致立即触发时钟中断，不知道你现在的代码中是否还保留这行，如果还有这行的话，可以删掉这行试试。（按我们 CPU 正常的执行速度来说，30 ms 可以执行很多条指令，应该是不至于一直出发时钟中断卡在时钟中断的处理程序中的

**Comment by SoftEgLi** [comment]
好像是msr daif,x9的问题，我把msr daif，x9删掉后好了，elapse设为1都能跑了。
