### ISSUE TITLE
不小心把远程服务器的仓库git init了，有办法恢复吗

### ISSUE THREAD

**Issue by SoftEgLi** [idlebo/OS-23Fall-FDU#9]
我VSCode开了多窗口，恍惚中使用远程服务器的窗口运行了git init。现在服务器上只有lab4的代码，历史记录都没了。请问有办法恢复吗？

**Comment by w568w** [comment]
`git init` 根据我的测试不会改变已有仓库的索引、工作区或历史记录。参考 [GIT-INIT(1)](https://git-scm.com/docs/git-init):

> **Running git init in an existing repository is safe. It will not overwrite things that are already there.** The primary reason for rerunning git init is to pick up newly added templates (or to move the repository to another place if --separate-git-dir is given).

请检查是否你使用了其他命令覆盖仓库。无论如何，`git log` 和 `git reflog` 是你对于已提交内容可查找的恢复方式。

**Comment by SoftEgLi** [comment]
我忘记切换出build目录了，仓库没丢，感谢助教提醒(o^▽^o)
